/******************************************************************************
 * @file    OpenGLContext.cpp
 * @author  Clarke Needles
 * @brief   OpenGL context creation and GLFW management implementation.
 ******************************************************************************/

#include "opengl_context.h"

#include <iostream>

OpenGLContext::OpenGLContext(
    int width,
    int height,
    const char* title
) : m_width(width), m_height(height)
{
    // Initialize GLFW
    if (!glfwInit())
    {
        std::cerr << "Failed to initialize GLFW\n";
        return;
    }

    /*
        Request OpenGL version

        3.3 Core is enough for:
        - shaders
        - VAOs
        - VBOs
        - textures
    */
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

    // Create window
    m_window = glfwCreateWindow(
        width,
        height,
        title,
        nullptr,
        nullptr
    );

    if (!m_window)
    {
        std::cerr << "Failed to create GLFW window\n";

        glfwTerminate();

        return;
    }

    // Activate OpenGL context
    glfwMakeContextCurrent(m_window);

    /*
        Enable VSync

        Prevents rendering faster than monitor refresh.
    */
    glfwSwapInterval(1);

    // Load OpenGL functions
    glewExperimental = GL_TRUE;

    if (glewInit() != GLEW_OK)
    {
        std::cerr << "Failed to initialize GLEW\n";
    }

    // Remove initial OpenGL error generated by GLEW
    glGetError();
}

OpenGLContext::~OpenGLContext()
{
    if (m_window)
    {
        glfwDestroyWindow(m_window);
    }

    glfwTerminate();
}

bool OpenGLContext::shouldClose() const
{
    return glfwWindowShouldClose( m_window);
}

void OpenGLContext::swapBuffers()
{
    glfwSwapBuffers(m_window);
}

void OpenGLContext::pollEvents()
{
    glfwPollEvents();
}

GLFWwindow* OpenGLContext::getWindow() const
{
    return m_window;
}

int OpenGLContext::getWidth() const
{
    return m_width;
}

int OpenGLContext::getHeight() const
{
    return m_height;
}